version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpassword
    ports:
      - "3306:3306"
    networks:
      - dev-network
    volumes:
      - mysql_data:/var/lib/mysql

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:mysql://mysql:3306/sonarqube?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: rootpassword
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - dev-network

networks:
  dev-network:

volumes:
  mysql_data:
