spring:
  datasource:
    url: jdbc:mysql://mysql:3306/springdb?useSSL=false&serverTimezone=UTC
    username: springuser
    password: springpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
